name: sporth
description: An application for sport's meetings.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0-beta

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  google_sign_in: ^6.0.2
  http: ^0.13.5
  image_picker: ^0.8.7+1
  intl: ^0.17.0
  path_provider: ^2.0.14
  provider: ^6.0.5
  share_plus: ^6.3.2
  table_calendar: ^3.0.0
  google_mobile_ads: 3.0.0
  flutter_native_splash: ^2.2.19
  
flutter_native_splash:
  android: true
  ios: true
  web: false
  
  background_image: "image/background_splash.png"
  image: "image/logo_transparente.png"

dev_dependencies:
  build_runner:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Assets to your application:
  assets:
    - image/
    - image/icons/
    - image/banners/
    - image/logros/
    - data/

  fonts:
    - family: Kanit
      fonts:
        - asset: font/Kanit-Regular.ttf
